//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektrikDunyasi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dergi
    {
        public int DergiId { get; set; }
        public string DergiBaslik { get; set; }
        public System.DateTime Tarih { get; set; }
        public string DergiUrl { get; set; }
        public string DergiDeleteUrl { get; set; }
        public string ImageUrl { get; set; }
        public string DeleteImageUrl { get; set; }
    }
}
