//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektrikDunyasi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElektKunye
    {
        public int KunyeId { get; set; }
        public string Imtyaz { get; set; }
        public string Sormlu { get; set; }
        public string YayinDanisman { get; set; }
        public string YayinKrl { get; set; }
        public string Reklam { get; set; }
        public string ReklamHalk { get; set; }
        public string Guney { get; set; }
        public string Kurye { get; set; }
        public string Ceviri { get; set; }
        public string Dogu { get; set; }
        public string Iran { get; set; }
        public string Misir { get; set; }
        public string Holland { get; set; }
        public string Poland { get; set; }
        public string Hukuk { get; set; }
        public string Dagitim { get; set; }
        public string Baski { get; set; }
        public string Yayin { get; set; }
        public string Type { get; set; }
        public string Year { get; set; }
    }
}
