//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektrikDunyasi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haberler
    {
        public int HaberId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string HaberBaslik { get; set; }
        public string HaberYazi { get; set; }
        public string HaberEkleyen { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string DeleteUrl { get; set; }
        public string Keywords { get; set; }
    }
}
