//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektrikDunyasi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DergiElektrikEntities : DbContext
    {
        public DergiElektrikEntities()
            : base("name=DergiElektrikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Haberler> Haberler { get; set; }
        public virtual DbSet<Rportaj> Rportaj { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Hakkimizda> Hakkimizda { get; set; }
        public virtual DbSet<SiteYonetim> SiteYonetim { get; set; }
        public virtual DbSet<Teknoloji> Teknoloji { get; set; }
        public virtual DbSet<Makaleler> Makaleler { get; set; }
        public virtual DbSet<Dergi> Dergi { get; set; }
        public virtual DbSet<EDergi> EDergi { get; set; }
        public virtual DbSet<LoginAdmin> LoginAdmin { get; set; }
        public virtual DbSet<ElektKunye> ElektKunye { get; set; }
        public virtual DbSet<LeftBanner> LeftBanner { get; set; }
        public virtual DbSet<MainBanner> MainBanner { get; set; }
        public virtual DbSet<RightBanner> RightBanner { get; set; }
        public virtual DbSet<AboneInfo> AboneInfo { get; set; }
        public virtual DbSet<Editor> Editor { get; set; }
        public virtual DbSet<Sektorden> Sektorden { get; set; }
        public virtual DbSet<stdImages> stdImages { get; set; }
        public virtual DbSet<Akedemisyen> Akedemisyen { get; set; }
    }
}
