//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektrikDunyasi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RightBanner
    {
        public int RightBannerId { get; set; }
        public string ImageUrl { get; set; }
        public string DeleteUrl { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
