//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektrikDunyasi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteYonetim
    {
        public int SıteID { get; set; }
        public string SiteBaslik { get; set; }
        public string SiteAciklama { get; set; }
        public string SiteKeywords { get; set; }
    }
}
